### PR TITLE
fix: write images to and from cache

### LINKED ISSUE #19: Build cache
There are two outcomes of this task:

1. Research how to enable and use build caching to skip image generation.
2. Document how to set up caching in README.

## Cloudflare

- Use [Build Caching](https://developers.cloudflare.com/pages/configuration/build-caching) (has to be enabled explicitly). Supports some major frameworks but not Remix. 

If Remix was supported, enabling Build Caching would theoretically be enough to cache the generated images, but now you get this:

```
Skipping build output cache as it's not supported for your project
```

## Vercel

- Use [Build caching](https://vercel.com/docs/deployments/troubleshoot-a-build#what-is-cached). I don't seen an explicit mention of Remix build cache path, but Vercel caches everything in `node_modules` across builds. The plugin can utilize that.

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #19 

## Changes

- Writes the generated images to the cache _and_ the output directory on a clean run.
- If the route hasn't been changed, and the cache is present, copies the generated images from the cache to the output directory, skipping the browser-screenshot phase entirely. 
- Renames `cache.json` to `manifest.json`. 
- Properly formats cache paths on non-Unix machines (uses `path.resolve()`).

### CODE REVIEW

File: src/plugin.ts [hunk 1]
```diff
@@ -334,7 +353,10 @@ export function openGraphImagePlugin(options: Options): Plugin {
 
     cache.set(route.id, {
       routeLastModifiedAt,
-      imagePaths: images.map((image) => image.path),
+      images: images.map((image) => ({
+        name: image.name,
+        outputPath: image.path,
```
Comment (kettanaito) [inline src/plugin.ts:358]: Store the original destination path of the image in cache. This way, the plugin can copy the image from cache to this path when applicable.

**Comment by kettanaito** [comment]
## Released: v0.3.5 🎉

This has been released in v0.3.5!

- 📄 [**Release notes**](https://github.com/kettanaito/remix-og-image/releases/tag/v0.3.5)
- 📦 [npm package](https://www.npmjs.com/package/remix-og-image/v/0.3.5)

Make sure to always update to the latest version (`npm i remix-og-image@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
